### ISSUE TITLE
Incorrect rendering, some files do not render

### ISSUE THREAD

**Issue by ghost** [tommyettinger/IsoVoxel#1]
Sprites are being rendered incorrectly for some reason. It looks like they are being rendered with the model rotated to one side a bit.
![image](https://cloud.githubusercontent.com/assets/5129595/7343033/e1bc563c-ecc4-11e4-828d-485ef6fea836.png)
![image](https://cloud.githubusercontent.com/assets/5129595/7343042/fc5620f4-ecc4-11e4-9bfc-ad43ae5a5aa8.png)
And I can't open one file out of the 5 files that I tried. It's called chr_custom_girl1. I'll include the archive with both of the models, http://www.mediafire.com/download/si78jmhc66aki11/IsoVoxel.rar

And I also have a request, which would be that the program would calculate the bounds by itself, which doesn't seem like it would be too hard to do.

This is a really great program. I was glad that I finally found something like this. Now if those bugs were gone it would be perfect.

Keep up the good work :)

**Comment by tommyettinger** [comment]
Good catch on both counts.  There was a bug that would only cause a crash if the palette wasn't changed from the default; this has been fixed in version 0.0.3 . Can you download https://github.com/tommyettinger/IsoVoxel/releases/tag/0.0.3 and see if it works better on chr_custom_girl1 ?  This release will use the size of the models unless a larger one was specified by the user, and it also will produce some images that haven't been shrunk down.  The shrinking is what causes the asymmetrical appearance of those images; it helps reduce the appearance of "staircase" voxels, making them more slope-like, but also makes some voxels take up more space than others.  The un-shrunken images this now generates next to the shrunken ones should have no asymmetry, and some tiny details will now be visible.

**Comment by tommyettinger** [comment]
Here's what the new ones look like:
![ship1_big_w](https://cloud.githubusercontent.com/assets/160684/7344139/fdf4f134-ec7d-11e4-9db2-d75101591e01.png)
![ship1_big_e](https://cloud.githubusercontent.com/assets/160684/7344143/07df24b2-ec7e-11e4-9f7c-0c876fd1405e.png)
![chr_custom_girl1_big_e](https://cloud.githubusercontent.com/assets/160684/7344153/29ff73e4-ec7e-11e4-8c6c-93019920650d.png)
![chr_custom_girl1_big_sw](https://cloud.githubusercontent.com/assets/160684/7344161/36122c44-ec7e-11e4-9211-33ea8ec10c18.png)

**Comment by ghost** [comment]
Those two models work great now (and a few others). And I really love the bigger renders of the models. It's just what I wanted. But now in this update, I can't manage to render some of the files that I was able to before. All of the models were rendered without entering the X, Y and Z bounds. Here are the errors it gave me:

> D:\Programs\MagicaVoxel\IsoVoxel>IsoVoxel.exe mini_ship2.vox
> 
> Unhandled Exception: System.IndexOutOfRangeException: Index was outside the boun
> ds of the array.
>    at IsoVoxel.PaletteDraw.renderSmart(MagicaVoxelData[] voxels, Byte xSize, Byt
> e ySize, Byte zSize, Direction dir, Boolean shrink)
>    at IsoVoxel.PaletteDraw.processUnitSmart(MagicaVoxelData[] parsed, String u,
> Byte xSize, Byte ySize, Byte zSize)
>   at IsoVoxel.PaletteDraw.Main(String[] args)
> 
> D:\Programs\MagicaVoxel\IsoVoxel>IsoVoxel.exe ship3.vox
> 
> Unhandled Exception: System.IndexOutOfRangeException: Index was outside the boun
> ds of the array.
>    at IsoVoxel.PaletteDraw.renderSmart(MagicaVoxelData[] voxels, Byte xSize, Byt
> e ySize, Byte zSize, Direction dir, Boolean shrink)
>    at IsoVoxel.PaletteDraw.processUnitSmart(MagicaVoxelData[] parsed, String u,
> Byte xSize, Byte ySize, Byte zSize)
>    at IsoVoxel.PaletteDraw.Main(String[] args)
> 
> D:\Programs\MagicaVoxel\IsoVoxel>IsoVoxel.exe ship2.vox
> 
> Unhandled Exception: System.IndexOutOfRangeException: Index was outside the boun
> ds of the array.
>    at IsoVoxel.PaletteDraw.renderSmart(MagicaVoxelData[] voxels, Byte xSize, Byt
> e ySize, Byte zSize, Direction dir, Boolean shrink)
>    at IsoVoxel.PaletteDraw.processUnitSmart(MagicaVoxelData[] parsed, String u,
> Byte xSize, Byte ySize, Byte zSize)
>    at IsoVoxel.PaletteDraw.Main(String[] args)

Here are the files that gave me these errors, http://www.mediafire.com/download/6h7wbeflv3z2qth/IsoVoxel%282%29.rar
As far as I understand from the error is that the bounds are at fault?

Edit: Also giving it the X, Y, Z values gives the same error.

**Comment by tommyettinger** [comment]
Yep, I screwed something up when I made the program try to figure out x,y,z sizes on its own.  I have a new version on the way. Here's a preview:
![ship2_big_ne](https://cloud.githubusercontent.com/assets/160684/7357480/eb00d6d6-ece3-11e4-8cb9-86f1de083e80.png)

**Comment by tommyettinger** [comment]
OK, can you try https://github.com/tommyettinger/IsoVoxel/releases/tag/0.0.4 now?  These models are fantastic, by the way, it's been nice seeing them render.
![ship2_big_n](https://cloud.githubusercontent.com/assets/160684/7357750/a5946cdc-ece5-11e4-8046-6e9a41d03b9d.png)
![ship3_big_e](https://cloud.githubusercontent.com/assets/160684/7357763/b33ba18e-ece5-11e4-9106-f98193b6115c.png)
![mini_ship2_big_nw](https://cloud.githubusercontent.com/assets/160684/7357773/c165a868-ece5-11e4-9a5b-1d4c3e97ebc7.png)

**Comment by ghost** [comment]
Everything seems to be working fine now. I've tested 7 different models and it gave me no errors. Thank you for your hard work! :)

**Comment by ghost** [comment]
There's still one issue with the outline that I found. I think it just doesn't fit into the bounds of the image.
![capture](https://cloud.githubusercontent.com/assets/5129595/7365504/91c1815e-ed99-11e4-9f8c-b409ea8038c5.PNG)
![mini_box_big_ne](https://cloud.githubusercontent.com/assets/5129595/7365670/0e486700-ed9b-11e4-82f8-fc4d05c307ee.png)

The file, http://www.mediafire.com/download/pllppagzz6zfo9k/mini_box.vox

**Comment by tommyettinger** [comment]
There's two factors at work here.  One is that a single voxel draws an outline directly above and below it, directly to its sides, AND at the corners formed between those positions.  This causes angles pointing toward the camera in iso mode to seem like they're more flat than they actually are.  However, the issue you encountered was an actual bug; it was drawing both iso and ortho a bit too low in the final image, and that could chop off a small amount of the outline if a corner contained a voxel.  https://github.com/tommyettinger/IsoVoxel/releases/tag/0.0.5 is out now.  It's possible this will have issues with very tall or very short models, but it seems to work so far.

**Comment by ghost** [comment]
Thanks again. I'll report any other bugs that I find. This is a really great piece of software. And I'm amazed that you are working on this project so passionately. Yet again, keep up the good work :)
