### ISSUE TITLE
Have the option to disable the outline

### ISSUE THREAD

**Issue by ghost** [tommyettinger/IsoVoxel#2]
I love the outline that the object is given after it is rendered. It really helps the object to stand out from the background. But the problem is that sometimes you don't want the outline. You usually don't need an outline while working on background objects or tiles. It would be great if you could disable it on some renders.
It'd be great if you could render an object with an outline by simply typing

> IsoVoxel.exe file.vox

And let's say disable the outline by typing

> IsoVoxel.exe file.vox nooutline

I think that adding this feature would allow people to save time as removing the outline manually on an image editor wouldn't be necessary.

P.S.
I'm sorry if I'm bothering you too much. You already helped me a lot by improving your code in the past few days.

**Comment by tommyettinger** [comment]
This is a good idea, but do you still want "inner outlines?" The black outline is easy for me to disable, but I'm not sure if it's desirable to completely remove the darker-colored lines between distant parts of the model (like when you look at the sails of your ship from head-on, there's an outline in gray drawn where one white sail is in front of another).
![ship2_big_n](https://cloud.githubusercontent.com/assets/160684/7382412/66d539f2-edc3-11e4-97cd-2f8eab25b88e.png)
I'll see if I can make a few options. I think I will have it so `IsoVoxel.exe file.vox outline=none` draws absolutely no outlines, inner or outer, `IsoVoxel.exe file.vox outline=partial` draws only the inner outlines, `IsoVoxel.exe file.vox outline=light` draws the outer outline with a lighter color and leaves inner outlines unchanged (I use this for background tiles in PixVoxelAssets, and I'll probably just copy in code from there), and `IsoVoxel.exe file.vox outline=full` (the default, not really needed) draws all outlines as it does now.  If numeric arguments are present (x y z sizes), it will read those first before seeing if there's an outline argument.

P.S. I'm just glad someone found this useful!  Those ships are really good, and I'm curious what they'll be used for.

**Comment by ghost** [comment]
Having a lot of options is a good thing. I really see now why I'd need the `outline=partial`, as the sails would merge with one another without it. But having an option to disable everything might be useful too.

Well, I don't know if the models will be used for anything. I'm thinking of working on a game as a hobby, for learning purposes, but I'm known to give up easily.

**Comment by tommyettinger** [comment]
OK, it's in release 0.0.6 now. https://github.com/tommyettinger/IsoVoxel/releases/tag/0.0.6
It looks like this with some different options:
Light:
![ship2_big_n](https://cloud.githubusercontent.com/assets/160684/7386092/a83f1b6a-ee04-11e4-964f-2baaab4091f7.png)
Partial:
![ship3_big_s](https://cloud.githubusercontent.com/assets/160684/7386098/b339805a-ee04-11e4-8afd-0eaa32765447.png)
None:
![ship1_big_w](https://cloud.githubusercontent.com/assets/160684/7386100/c24a6a8c-ee04-11e4-8046-bcd571421f72.png)

**Comment by ghost** [comment]
I really like the `outline=light` option. And the `outline=none` will be great for making seamless tiles. I tried rendering a couple of models and everything seems to be working. Great job as always. Thank you :)
