### ISSUE TITLE
No SW View for the Normal Isometric View

### ISSUE THREAD

**Issue by miredge** [tommyettinger/IsoVoxel#6]
![image](https://user-images.githubusercontent.com/14828040/44955804-cf020900-aeb9-11e8-8f7f-586e697a5a43.png)

On the 0-0-12 version I don't have any SW Sprite for the Normal Iso view.

**Comment by tommyettinger** [comment]
I'll take a look as soon as I can, later today. It looks like some of the positions IsoVoxel uses are also incorrect, such as if you compare Armchair_E and Armchair_Big_E... It definitely needs SW; I wonder what is preventing that from saving.

**Comment by tommyettinger** [comment]
Uh, maybe check at the very end of the alphabetical order... it looks like those files are sorted alphabetically and all the Armchair_Size1, Armchair_Size2, etc. would be between Armchair_SE and Armchair_SW. I just almost missed that file in my own render test, until I checked at the very end (I only have two images at the very end that are the normal, smaller kind of render, and they are the SW and W directions)

**Comment by miredge** [comment]
Yes that's it Sorry ! it was kind of silly x).

Love Isovoxel, thanks for your hardwork!

**Comment by tommyettinger** [comment]
Glad everything's OK, but now I'm curious about why some of the chairs in your folder screenshot have very different positions inside the bounds of the render... I'll try to reproduce the positioning quirk over here, and I might start another issue myself if I find a discrepancy in how "Big" renders are positioned relative to other ones.

**Comment by miredge** [comment]
It's because the object is contain in a big transparent space if I trim the space the position problem disappear.

**Comment by tommyettinger** [comment]
Huh, I guess that makes sense, but I was just wondering why some of the renders push the chair off to the edge of the image and some of them don't. I'm guessing some of IsoVoxel's code that is supposed to center the model during rendering (including any transparent space) either isn't centering correctly, isn't using the sizes given at the command line, or is miscalculating sizes if the command line had a default "0" value. If it isn't an issue for you I won't try changing things just yet.
