### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by superfrantv** [tommyettinger/IsoVoxel#9]
Hello, you are still active?

I very very like this progamm.
is it possible to create Isometric Spritesheets from .obj files? or .ply files?
i need a obj (with animation) convert to isometic spritesheet.

if you are interested, let me know

thank you and sorry for my bad english :D

**Comment by tommyettinger** [comment]
Hi, yes I'm still active. Thank you!

IsoVoxel just renders MagicaVoxel .vox files to pixel-art-style images. You may be able to import .obj into MagicaVoxel, save as .vox, and use that here, but you would lose lots of detail in your .obj models. It's probably best in your case to pre-render the .obj animations in a different program like Blender that can open .obj files. You may be able to use a "flat shading" or "toon shading" or "cel shading" effect in Blender's rendering to make the result look more like the style IsoVoxel produces. An extra advantage to doing this is that you aren't limited at all for which way a model can face, and you can turn them as much as you like. If you use an orthographic camera (not perspective), then the renders will look like isometric views if the camera angle is right.

If you have the time to learn how to use your .obj animations without rendering them to spritesheets, you might want to do that instead; a single .obj file with lots of poses and animations would have to render to dozens or hundreds of single-frame image files, and that many pre-rendered images are probably much larger in file size than most .obj files.

IsoVoxel is only meant to take voxel models from MagicaVoxel and render them with some minor adjustments as a pixel-art-like style. Adding .obj support to IsoVoxel doesn't really make sense, considering how the program works.

Thank you for your interest, and have a good day.

Also, your English is fine. :smiley:
